name: Static Page Deployment Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir -p build
          cp -r public/* build/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: |
          if [ -f public/index.html ]; then
            echo "Test passed: index.html exists."
          else
            echo "Test failed: index.html does not exist."
            exit 1
          fi


  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: victor 
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/victor/shiny-spork
            git pull origin main
            sudo cp -r /home/victor/shiny-spork/* /var/www/html/
            sudo systemctl restart nginx
